"$schema" = "https://schema.tauri.app/config/2"
productName = "Trellis App"
version = "0.1.0"
identifier = "com.trellis.app"

[build]
frontendDist = "../client/dist"

[app]
withGlobalTauri = true

[[app.windows]]
title = "Trellis App"
width = 1024
height = 768
devtools = true
